services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: smartlogix
      POSTGRES_PASSWORD: smartlogix123
      POSTGRES_DB: smartlogix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartlogix"]
      interval: 5s
      timeout: 5s
      retries: 10

  ms-usuarios:
    build: ./ms-usuarios/ms-usuarios
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogix
      SPRING_DATASOURCE_USERNAME: smartlogix
      SPRING_DATASOURCE_PASSWORD: smartlogix123
    depends_on:
      postgres:
        condition: service_healthy

  ms-inventario:
    build: ./ms-inventario/ms-inventario
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogix
      SPRING_DATASOURCE_USERNAME: smartlogix
      SPRING_DATASOURCE_PASSWORD: smartlogix123
    depends_on:
      postgres:
        condition: service_healthy

  ms-pedidos:
    build: ./ms-pedidos/ms-pedidos
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogix
      SPRING_DATASOURCE_USERNAME: smartlogix
      SPRING_DATASOURCE_PASSWORD: smartlogix123
    depends_on:
      postgres:
        condition: service_healthy

  ms-envios:
    build: ./ms-envios/ms-envios
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogix
      SPRING_DATASOURCE_USERNAME: smartlogix
      SPRING_DATASOURCE_PASSWORD: smartlogix123
    depends_on:
      postgres:
        condition: service_healthy

  ms-notificaciones:
    build: ./ms-notificaciones/ms-notificaciones
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogix
      SPRING_DATASOURCE_USERNAME: smartlogix
      SPRING_DATASOURCE_PASSWORD: smartlogix123
    depends_on:
      postgres:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway/api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - ms-usuarios
      - ms-inventario
      - ms-pedidos
      - ms-envios
      - ms-notificaciones

volumes:
  postgres_data: